### ISSUE TITLE
Push of a non-existant image blows up with `index out of range`

### ISSUE THREAD

**Issue by relistan** [dogestry/dogestry#77]
```
$ DOCKER_HOST=tcp://docker2:2375 dogestry push s3://mybucket/
Using docker endpoint for push: tcp://docker2:2375
Remote: s3(bucket=mybucket, region=us-east-1)
Error getting image history: no such image
Checking layers on remote
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/dogestry/dogestry/cli.(*DogestryCli).exportToFiles(0xc2080a20b0, 0x7fff5fbff938, 0x1e, 0x1025488, 0xc208042240, 0xc2080102a0, 0x61, 0x0, 0x0)
	/Users/kmatthias/go/src/github.com/dogestry/dogestry/cli/push.go:223 +0x814
github.com/dogestry/dogestry/cli.(*DogestryCli).CmdPush(0xc2080a20b0, 0xc20800a020, 0x2, 0x2, 0x0, 0x0)
	/Users/kmatthias/go/src/github.com/dogestry/dogestry/cli/push.go:58 +0x711
reflect.callMethod(0xc20803cf30, 0xc20830dda0)
	/usr/local/go/src/reflect/value.go:605 +0x179
reflect.methodValueCall(0xc20800a020, 0x2, 0x2, 0xc20803cf30, 0xc20803e001, 0x1, 0x1, 0x12, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/asm_amd64.s:29 +0x36
github.com/dogestry/dogestry/cli.(*DogestryCli).RunCmd(0xc2080a20b0, 0xc20800a010, 0x3, 0x3, 0x0, 0x0)
	/Users/kmatthias/go/src/github.com/dogestry/dogestry/cli/cli.go:122 +0x29e
main.main()
	/Users/kmatthias/go/src/github.com/dogestry/dogestry/main.go:81 +0x4be
```

**Comment by dselans** [comment]
Don't think is an issue any longer - I fixed this panic a couple months ago in this commit: https://github.com/dogestry/dogestry/commit/dd44b6f2fdf7ff8be2f69d920ba701808c9ab481
